name: CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' # Fetches the submodules

      - name: Set up CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Build project with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ env.BUILD_TYPE }}
      # New step for installing Valgrind
      - name: Install Valgrind
        run: sudo apt-get install -y valgrind

      # New step for running tests with Valgrind
      - name: Valgrind Test
        working-directory: build
        run: valgrind --leak-check=full --error-exitcode=1 ./tests/torrent_test